version: '2'
services:
  app:
    container_name: docker-coursecontent
    restart: always
    build: .
    ports: 
      - '3333:3333'
    links:
      - mongo
    environment: 
      - MONGO_URI=mongodb://max:reviews7@ds151970.mlab.com:51970/reviews
  mongo: 
    container_name: mongo-reviews
    image: mongo
    ports: 
      - '27019:27017'